jobs:
  - job: ${{ parameters.host }}
    # NOTE(compnerd) disable non-x64 builds as they are currently broken :(
    condition: eq( '${{ parameters.host }}', 'x64' )
    steps:
      - download: icu
        artifact: icu-${{ parameters.platform }}-${{ parameters.host }}
        displayName: download ICU

      - script: |
          git config --global --add core.autocrlf false
          git config --global --add core.symlinks true
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
        displayName: Enable symbolic links, disable line ending conversion

      # The checkout list has to match with the windows-sdk.yml checkout list.
      # Otherwise Azure will create different directories for each build.
      - checkout: self
        displayName: checkout compnerd/swift-build

      - task: BatchScript@1
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
        displayName: VsDevCmd.bat
        inputs:
          filename: C:/Program Files (x86)/Microsoft Visual Studio/${{ parameters.VisualStudio }}/Common7/Tools/VsDevCmd.bat
          arguments: -no_logo -arch=x64 -host_arch=x64
          modifyEnvironment: true

      - task: MSBuild@1
        displayName: ${{ parameters.platform }}-icu-${{ parameters.proc }}.msi
        inputs:
          solution: $(Build.SourcesDirectory)/wix/windows-icu.wixproj
          msbuildArguments: /p:RunWixToolsOutOfProc=true -p:OutputPath=$(Build.BinariesDirectory)\icu-msi\ -p:IntermediateOutputPath=$(Build.BinariesDirectory)\icu-msi\ -p:ICU_ROOT=$(Pipeline.Workspace)/icu/icu-${{ parameters.platform }}-${{ parameters.host }}

      - task: DownloadSecureFile@1
        name: certificate
        inputs:
          secureFile: dt.compnerd.org.p12

      - script: |
          signtool sign /f $(certificate.secureFilePath) /p $(CERTIFICATE_PASSWORD) /tr http://timestamp.digicert.com /fd sha256 /td sha256 $(Build.BinariesDirectory)/icu-msi/icu.msi
        displayName: Sign ${{ parameters.platform }}-icu-${{ parameters.proc }}.msi

      - publish: $(Build.BinariesDirectory)/icu-msi/icu.msi
        artifact: ${{ parameters.platform }}-icu-${{ parameters.proc }}.msi
