parameters:
  - name: SWIFT_OPTIONS
    type: string
    default: ''

  - name: VisualStudio
    type: string
    default: ''

  - name: arch
    type: string

  - name: host
    type: string

  - name: platform
    type: string

  - name: triple
    type: string

  - name: os
    type: string

  - name: proc
    type: string

jobs:
  - job: ${{ parameters.host }}
    # NOTE(compnerd) disable non-x64 builds as they are currently broken :(
    condition: eq( '${{ parameters.host }}', 'x64' )
    variables:
      toolchain.directory: $(Pipeline.Workspace)/toolchain-windows-x64/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain

      curl.version: development
      icu.version: 64
      xml2.version: development
      zlib.version: 1.2.11

      curl.directory: $(Pipeline.Workspace)/curl/curl-${{ parameters.platform }}-${{ parameters.host }}/Library/libcurl-$(curl.version)
      icu.directory: $(Pipeline.Workspace)/icu/icu-${{ parameters.platform }}-${{ parameters.host }}/Library/icu-$(icu.version)
      xml2.directory: $(Pipeline.Workspace)/xml2/xml2-${{ parameters.platform }}-${{ parameters.host }}/Library/libxml2-$(xml2.version)
      zlib.directory: $(Pipeline.Workspace)/zlib/zlib-${{ parameters.platform }}-${{ parameters.host }}/Library/zlib-$(zlib.version)

      platform.directory: $(Build.StagingDirectory)/sdk-${{ parameters.platform }}-${{ parameters.host }}/Library/Developer/Platforms/${{ parameters.os }}.platform
      sdk.directory: $(platform.directory)/Developer/SDKs/${{ parameters.os }}.sdk

      install.directory: $(sdk.directory)/usr
      xctest.install.directory: $(platform.directory)/Developer/Library/XCTest-development/usr
    steps:
      - download: current
        artifact: toolchain-windows-x64
        displayName: 'download toolchain'
      - download: icu
        artifact: icu-${{ parameters.platform }}-${{ parameters.host }}
        displayName: 'download ICU'
      - download: xml2
        artifact: xml2-${{ parameters.platform }}-${{ parameters.host }}
        displayName: 'download XML2'
      - download: curl
        artifact: curl-${{ parameters.platform }}-${{ parameters.host }}
        displayName: 'download CURL'
      - download: zlib
        artifact: zlib-${{ parameters.platform }}-${{ parameters.host }}
        displayName: 'download zlib'
      - script: |
          git config --global --add core.autocrlf false
          git config --global --add core.symlinks true
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
        displayName: 'Enable symbolic links, disable line ending conversion'
      - checkout: self
      - checkout: apple/llvm-project
        displayName: 'checkout apple/llvm-project'
      - checkout: apple/swift
        displayName: 'checkout apple/swift'
      - checkout: apple/swift-corelibs-libdispatch
        displayName: 'checkout apple/swift-corelibs-libdispatch'
      - checkout: apple/swift-corelibs-foundation
        displayName: 'checkout apple/swift-corelibs-foundation'
      - checkout: apple/swift-corelibs-xctest
        displayName: 'checkout apple/swift-corelibs-xctest'
      - script: |
          git config --global user.name 'builder'
          git config --global user.email 'builder@compnerd.org'

          call :ApplyPatches "%SWIFT_PR%" swift
          call :ApplyPatches "%DISPATCH_PR%" swift-corelibs-libdispatch
          call :ApplyPatches "%FOUNDATION_PR%" swift-corelibs-foundation
          call :ApplyPatches "%XCTEST_PR%" swift-corelibs-xctest

          goto :eof

          :ApplyPatches
          setlocal
          set list=%~1
          set repository=%~2
          for /F "tokens=1*" %%P in ("%list%") do (
            git -C %repository% fetch origin pull/%%P/head
            git -C %repository% cherry-pick FETCH_HEAD
            if not "%%Q" == "" call :ApplyPatches "%%Q" %repository%
          )
          endlocal
          goto :eof
        displayName: 'Apply Patches'
      - task: BatchScript@1
        inputs:
          filename: C:/Program Files (x86)/Microsoft Visual Studio/${{ parameters.VisualStudio }}/Common7/Tools/VsDevCmd.bat
          arguments: -no_logo -arch=${{ parameters.host }} -host_arch=x64
          modifyEnvironment: true
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
        displayName: 'vsvarsall.bat'
      - task: CmdLine@2
        inputs:
          script: |
            echo ##vso[task.prependpath]$(toolchain.directory)/usr/bin
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
        displayName: 'Update PATH'
      - script: |
          copy $(Build.SourcesDirectory)\swift\stdlib\public\Platform\ucrt.modulemap "%UniversalCRTSdkDir%\Include\%UCRTVersion%\ucrt\module.modulemap"
          copy $(Build.SourcesDirectory)\swift\stdlib\public\Platform\visualc.modulemap "%VCToolsInstallDir%\include\module.modulemap"
          copy $(Build.SourcesDirectory)\swift\stdlib\public\Platform\visualc.apinotes "%VCToolsInstallDir%\include\visualc.apinotes"
          copy $(Build.SourcesDirectory)\swift\stdlib\public\Platform\winsdk.modulemap "%UniversalCRTSdkDir%\Include\%UCRTVersion%\um\module.modulemap"
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
        displayName: 'Configure SDK'
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '2.7.x'
        name: python
        continueOnError: true

      - task: CMake@1
        displayName: Configure LLVM
        inputs:
          cmakeArgs:
            -G Ninja
            -S $(Build.SourcesDirectory)/llvm-project/llvm
            -B $(Build.BinariesDirectory)/llvm
            -C $(Build.SourcesDirectory)/swift-build/cmake/caches/${{ parameters.platform }}-${{ parameters.arch }}.cmake
            -D CMAKE_BUILD_TYPE=Release
            -D LLVM_HOST_TRIPLE=${{ parameters.triple }}

      - task: CMake@1
        displayName: Configure Swift Standard Library
        inputs:
          cmakeArgs:
            -G Ninja
            -S $(Build.SourcesDirectory)/swift
            -B $(Build.BinariesDirectory)/swift-stdlib
            -C $(Build.SourcesDirectory)/swift-build/cmake/caches/${{ parameters.platform }}-${{ parameters.arch }}-clang.cmake
            -C $(Build.SourcesDirectory)/swift-build/cmake/caches/swift-stdlib-${{ parameters.platform }}-${{ parameters.arch }}.cmake
            -D CMAKE_BUILD_TYPE=Release
            -D LLVM_DIR=$(Build.BinariesDirectory)/llvm/lib/cmake/llvm
            -D SWIFT_NATIVE_SWIFT_TOOLS_PATH=$(toolchain.directory)/usr/bin
            -D CMAKE_INSTALL_PREFIX=$(install.directory)
            ${{ parameters.SWIFT_OPTIONS }}

      - task: CMake@1
        displayName: Build Swift Standard Library
        inputs:
          cmakeArgs: --build $(Build.BinariesDirectory)/swift-stdlib

      - task: CMake@1
        displayName: Install Swift Standard Library
        inputs:
          cmakeArgs: --build $(Build.BinariesDirectory)/swift-stdlib --target install

      - task: CMake@1
        displayName: Configure libdispatch
        inputs:
          workingDirectory: $(Build.BinariesDirectory)/libdispatch
          cmakeArgs:
            -G Ninja
            -S $(Build.SourcesDirectory)/swift-corelibs-libdispatch
            -B $(Build.BinariesDirectory)/libdispatch
            -C $(Build.SourcesDirectory)/swift-build/cmake/caches/${{ parameters.platform }}-${{ parameters.arch }}-clang.cmake
            -D CMAKE_Swift_SDK=$(sdk.directory)
            -C $(Build.SourcesDirectory)/swift-build/cmake/caches/${{ parameters.platform }}-${{ parameters.arch }}-swift-flags.cmake
            -D CMAKE_BUILD_TYPE=Release
            -D CMAKE_INSTALL_PREFIX=$(install.directory)
            -D BUILD_TESTING=YES
            -D ENABLE_SWIFT=YES

      - task: CMake@1
        displayName: Build libdispatch
        inputs:
          cmakeArgs: --build $(Build.BinariesDirectory)/libdispatch

      - script: |
          echo ##vso[task.setvariable variable=CTEST_OUTPUT_ON_FAILURE]1
        condition: eq( variables['Agent.OSArchitecture'], '${{ parameters.host }}' )
        displayName: Configure CTest

      - task: CMake@1
        displayName: Test libdispatch
        inputs:
          cmakeArgs: --build $(Build.BinariesDirectory)/libdispatch --target ExperimentalTest
        condition: eq( variables['Agent.OSArchitecture'], '${{ parameters.host }}' )
        continueOnError: true

      - task: PublishTestResults@2
        condition: and( eq( variables['Agent.OSArchitecture'], '${{ parameters.host }}' ), succeededOrFailed() )
        displayName: Publish libdispatch test results
        inputs:
          testResultsFormat: cTest
          testResultsFiles: $(Build.BinariesDirectory)/libdispatch/Testing/*/Test.xml

      - task: CopyFiles@2
        displayName: 'Workaround CMake<3.16'
        inputs:
          sourceFolder: $(Build.BinariesDirectory)/libdispatch
          contents: swiftDispatch.lib
          targetFolder: $(Build.BinariesDirectory)/libdispatch/src/swift

      - task: CMake@1
        displayName: Configure Foundation
        inputs:
          workingDirectory: $(Build.BinariesDirectory)/foundation
          cmakeArgs:
            -G Ninja
            -S $(Build.SourcesDirectory)/swift-corelibs-foundation
            -B $(Build.BinariesDirectory)/foundation
            -C $(Build.SourcesDirectory)/swift-build/cmake/caches/${{ parameters.platform }}-${{ parameters.arch }}-clang.cmake
            -D CMAKE_Swift_SDK=$(sdk.directory)
            -C $(Build.SourcesDirectory)/swift-build/cmake/caches/${{ parameters.platform }}-${{ parameters.arch }}-swift-flags.cmake
            -D CMAKE_BUILD_TYPE=Release
            -D CMAKE_INSTALL_PREFIX=$(install.directory)
            -D ZLIB_LIBRARY=$(zlib.directory)/usr/lib/zlibstatic.lib
            -D ZLIB_INCLUDE_DIR=$(zlib.directory)/usr/include
            -D CURL_LIBRARY=$(curl.directory)/usr/lib/libcurl.lib
            -D CURL_INCLUDE_DIR=$(curl.directory)/usr/include
            -D ICU_INCLUDE_DIR=$(icu.directory)/usr/include
            -D ICU_UC_LIBRARY=$(icu.directory)/usr/lib/icuuc$(icu.version).lib
            -D ICU_UC_LIBRARY_RELEASE=$(icu.directory)/usr/lib/icuuc$(icu.version).lib
            -D ICU_I18N_LIBRARY=$(icu.directory)/usr/lib/icuin$(icu.version).lib
            -D ICU_I18N_LIBRARY_RELEASE=$(icu.directory)/usr/lib/icuin$(icu.version).lib
            -D LIBXML2_LIBRARY=$(xml2.directory)/usr/lib/libxml2s.lib
            -D LIBXML2_INCLUDE_DIR=$(xml2.directory)/usr/include/libxml2
            -D dispatch_DIR=$(Build.BinariesDirectory)/libdispatch/cmake/modules
            -D CURL_DIR=$(curl.directory)/usr/lib/cmake/CURL
            -D ENABLE_TESTING=NO

      - task: CMake@1
        displayName: Build Foundation
        inputs:
          cmakeArgs: --build $(Build.BinariesDirectory)/foundation

      - task: CMake@1
        displayName: Configure XCTest
        inputs:
          workingDirectory: $(Build.BinariesDirectory)/xctest
          cmakeArgs:
            -G Ninja
            -S $(Build.SourcesDirectory)/swift-corelibs-xctest
            -B $(Build.BinariesDirectory)/xctest
            -C $(Build.SourcesDirectory)/swift-build/cmake/caches/${{ parameters.platform }}-${{ parameters.arch }}-clang.cmake
            -D CMAKE_Swift_SDK=$(sdk.directory)
            -C $(Build.SourcesDirectory)/swift-build/cmake/caches/${{ parameters.platform }}-${{ parameters.arch }}-swift-flags.cmake
            -D CMAKE_BUILD_TYPE=Release
            -D CMAKE_INSTALL_PREFIX=$(xctest.install.directory)
            -D ENABLE_TESTING=NO
            -D dispatch_DIR=$(Build.BinariesDirectory)/libdispatch/cmake/modules
            -D Foundation_DIR=$(Build.BinariesDirectory)/foundation/cmake/modules

      - task: CMake@1
        displayName: Build XCTest
        inputs:
          cmakeArgs: --build $(Build.BinariesDirectory)/xctest

      - task: CMake@1
        condition: eq( variables['Agent.OSArchitecture'], '${{ parameters.host }}' )
        displayName: Re-Configure Foundation
        inputs:
          workingDirectory: $(Build.BinariesDirectory)/foundation
          cmakeArgs:
            -G Ninja
            -S $(Build.SourcesDirectory)/swift-corelibs-foundation
            -B $(Build.BinariesDirectory)/foundation
            -C $(Build.SourcesDirectory)/swift-build/cmake/caches/${{ parameters.platform }}-${{ parameters.arch }}-clang.cmake
            -D CMAKE_Swift_SDK=$(sdk.directory)
            -C $(Build.SourcesDirectory)/swift-build/cmake/caches/${{ parameters.platform }}-${{ parameters.arch }}-swift-flags.cmake
            -D CMAKE_BUILD_TYPE=Release
            -D CMAKE_INSTALL_PREFIX=$(install.directory)
            -D ZLIB_LIBRARY=$(zlib.directory)/usr/lib/zlibstatic.lib
            -D ZLIB_INCLUDE_DIR=$(zlib.directory)/usr/include
            -D CURL_LIBRARY=$(curl.directory)/usr/lib/libcurl.lib
            -D CURL_INCLUDE_DIR=$(curl.directory)/usr/include
            -D ICU_INCLUDE_DIR=$(icu.directory)/usr/include
            -D ICU_UC_LIBRARY=$(icu.directory)/usr/lib/icuuc$(icu.version).lib
            -D ICU_UC_LIBRARY_RELEASE=$(icu.directory)/usr/lib/icuuc$(icu.version).lib
            -D ICU_I18N_LIBRARY=$(icu.directory)/usr/lib/icuin$(icu.version).lib
            -D ICU_I18N_LIBRARY_RELEASE=$(icu.directory)/usr/lib/icuin$(icu.version).lib
            -D LIBXML2_LIBRARY=$(xml2.directory)/usr/lib/libxml2s.lib
            -D LIBXML2_INCLUDE_DIR=$(xml2.directory)/usr/include/libxml2
            -D dispatch_DIR=$(Build.BinariesDirectory)/libdispatch/cmake/modules
            -D CURL_DIR=$(curl.directory)/usr/lib/cmake/CURL
            -D ENABLE_TESTING=YES
            -D XCTest_DIR=$(Build.BinariesDirectory)/xctest/cmake/modules

      - task: CMake@1
        condition: eq( variables['Agent.OSArchitecture'], '${{ parameters.host }}' )
        displayName: Re-build Foundation
        inputs:
          cmakeArgs: --build $(Build.BinariesDirectory)/foundation

      - script: |
          echo ##vso[task.setvariable variable=CTEST_OUTPUT_ON_FAILURE]1
        condition: eq( variables['Agent.OSArchitecture'], '${{ parameters.host }}' )
        displayName: Configure CTest

      - script: |
          echo ##vso[task.setvariable variable=PATH]$(icu.directory)/usr/bin;$(Build.BinariesDirectory)/swift-stdlib/bin;$(Build.BinariesDirectory)/libdispatch;$(Build.BinariesDirectory)/foundation/Foundation;$(Build.BinariesDirectory)/xctest;%PATH%;%ProgramFiles%\Git\usr\bin
        condition: eq( variables['Agent.OSArchitecture'], '${{ parameters.host }}' )
        displayName: Update PATH

      - task: CMake@1
        condition: eq( variables['Agent.OSArchitecture'], '${{ parameters.host }}' )
        continueOnError: true
        displayName: Test Foundation
        inputs:
          cmakeArgs: --build $(Build.BinariesDirectory)/foundation --target test

      - task: PublishTestResults@2
        condition: and( eq( variables['Agent.OSArchitecture'], '${{ parameters.host }}' ), succeededOrFailed() )
        displayName: Publish Foundation test results
        inputs:
          testResultsFormat: cTest
          testResultsFiles: $(Build.BinariesDirectory)/foundation/Testing/*/Test.xml

      - task: CMake@1
        displayName: Install Foundation
        inputs:
          cmakeArgs: --build $(Build.BinariesDirectory)/foundation --target install

      - task: CMake@1
        displayName: Install XCTest
        inputs:
          cmakeArgs: --build $(Build.BinariesDirectory)/xctest --target install

      - task: CMake@1
        displayName: Install libdispatch
        inputs:
          cmakeArgs: --build $(Build.BinariesDirectory)/libdispatch --target install

      - publish: $(Build.StagingDirectory)/sdk-${{ parameters.platform }}-${{ parameters.host }}
        artifact: sdk-${{ parameters.platform }}-${{ parameters.host }}
