pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/android-sdk.yml
      - .ci/templates/android-sdk.yml
      - cmake/caches/android-aarch64.cmake
      - cmake/caches/android-aarch64-swift-flags.cmake
      - cmake/caches/android-armv7.cmake
      - cmake/caches/android-armv7-swift-flags.cmake
      - cmake/caches/android-i686.cmake
      - cmake/caches/android-i686-swift-flags.cmake
      - cmake/caches/android-x86_64.cmake
      - cmake/caches/android-x86_64-swift-flags.cmake
schedules:
  - cron: "0 6 * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Nightly (6:00 AM) build"
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/android-sdk.yml
      - .ci/templates/android-sdk.yml
      - cmake/caches/android-aarch64.cmake
      - cmake/caches/android-aarch64-swift-flags.cmake
      - cmake/caches/android-armv7.cmake
      - cmake/caches/android-armv7-swift-flags.cmake
      - cmake/caches/android-i686.cmake
      - cmake/caches/android-i686-swift-flags.cmake
      - cmake/caches/android-x86_64.cmake
      - cmake/caches/android-x86_64-swift-flags.cmake
jobs:
  - template: templates/android-sdk.yml
    parameters:
      image: windows-2019
      branch: master
      toolchain: 7

      arch: 'armv7'
      host: 'arm'
      triple: 'armv7-unknown-linux-androideabi'

  - template: templates/android-sdk.yml
    parameters:
      image: windows-2019
      branch: master
      toolchain: 7

      arch: 'aarch64'
      host: 'arm64'
      triple: 'aarch64-unknown-linux-android'

  - template: templates/android-sdk.yml
    parameters:
      image: windows-2019
      branch: master
      toolchain: 7

      arch: 'x86_64'
      host: 'x64'
      triple: 'x86_64-unknown-linux-android'

  - template: templates/android-sdk.yml
    parameters:
      image: windows-2019
      branch: master
      toolchain: 7

      arch: 'i686'
      host: 'x86'
      triple: 'i686-unknown-linux-android'
