pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/android-sdk.yml
      - .ci/templates/android-sdk.yml
      - cmake/caches/android-aarch64.cmake
      - cmake/caches/android-aarch64-swift-flags.cmake
      - cmake/caches/android-armv7.cmake
      - cmake/caches/android-armv7-swift-flags.cmake
      - cmake/caches/android-i686.cmake
      - cmake/caches/android-i686-swift-flags.cmake
      - cmake/caches/android-x86_64.cmake
      - cmake/caches/android-x86_64-swift-flags.cmake
resources:
  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: refs/heads/swift/master
      endpoint: GitHub
    - repository: apple/swift
      type: github
      name: apple/swift
      ref: refs/heads/master
      endpoint: GitHub
    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      ref: refs/heads/master
      endpoint: GitHub
    - repository: apple/swift-corelibs-foundation
      type: github
      name: apple/swift-corelibs-foundation
      ref: refs/heads/master
      endpoint: GitHub
    - repository: apple/swift-corelibs-xctest
      type: github
      name: apple/swift-corelibs-xctest
      ref: refs/heads/master
      endpoint: GitHub
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/android-sdk.yml
      - .ci/templates/android-sdk.yml
      - cmake/caches/android-aarch64.cmake
      - cmake/caches/android-aarch64-swift-flags.cmake
      - cmake/caches/android-armv7.cmake
      - cmake/caches/android-armv7-swift-flags.cmake
      - cmake/caches/android-i686.cmake
      - cmake/caches/android-i686-swift-flags.cmake
      - cmake/caches/android-x86_64.cmake
      - cmake/caches/android-x86_64-swift-flags.cmake
jobs:
  - template: templates/android-sdk.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'
      toolchain: 7

      arch: 'armv7'
      host: 'arm'
      triple: 'armv7-unknown-linux-androideabi'

  - template: templates/android-sdk.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'
      toolchain: 7

      arch: 'aarch64'
      host: 'arm64'
      triple: 'aarch64-unknown-linux-android'

  - template: templates/android-sdk.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'
      toolchain: 7

      arch: 'x86_64'
      host: 'x64'
      triple: 'x86_64-unknown-linux-android'

  - template: templates/android-sdk.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'
      toolchain: 7

      arch: 'i686'
      host: 'x86'
      triple: 'i686-unknown-linux-android'
