name: toolchain
pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/azure-pipelines-aws-agent.yml
      - .ci/templates/toolchain.yml
jobs:
  - job: windows_x64
    # TODO(compnerd) move to Facebook pool
    pool: Default
    variables:
      arch: x86_64
      host: x64
      platform: windows

      triple: x86_64-unknown-windows-msvc

      install.directory: $(Build.StagingDirectory)/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr

      icu.version : 64
      icu.directory: $(System.ArtifactsDirectory)/icu-$(platform)-$(host)/ICU-$(icu.version)

      llvm.extra_cmake_flags: -DLLVM_PARALLEL_LINK_JOBS=2
      swift.extra_cmake_flags: -DSWIFT_WINDOWS_x86_64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_x86_64_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_x86_64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_x86_64_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DSWIFT_PARALLEL_LINK_JOBS=8 -DSWIFT_BUILD_DYNAMIC_SDK_OVERLAY=YES -DSWIFT_BUILD_DYNAMIC_STDLIB=YES
      lldb.extra_cmake_flags: -DLLDB_DISABLE_PYTHON=YES
    steps:
    - task: BatchScript@1
      inputs:
        filename: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat
        arguments: -no_logo -arch=x64 -host_arch=x64
        modifyEnvironment: true
      displayName: 'vcvarsall.bat'
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '2.7.x'
    - script: |
        echo "##vso[task.setvariable variable=PATH]$(install.directory)/bin;%PATH%"
      displayName: 'Update PATH'
    # TODO(compnerd) figure out how to account for patches to these files
    - script: |
        curl -L "https://raw.githubusercontent.com/apple/swift/master/stdlib/public/Platform/ucrt.modulemap" -o "%UniversalCRTSdkDir%/Include/%UCRTVersion%/ucrt/module.modulemap"
        curl -L "https://raw.githubusercontent.com/apple/swift/master/stdlib/public/Platform/visualc.modulemap" -o "%VCToolsInstallDir%/include/module.modulemap"
        curl -L "https://raw.githubusercontent.com/apple/swift/master/stdlib/public/Platform/visualc.apinotes" -o "%VCToolsInstallDir%/include/visualc.apinotes"
        curl -L "https://raw.githubusercontent.com/apple/swift/master/stdlib/public/Platform/winsdk.modulemap" -o "%UniversalCRTSdkDir%/Include/%UCRTVersion%/um/module.modulemap"
      displayName: 'Configure SDK'
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: specific
        project: '3133d6ab-80a8-4996-ac4f-03df25cd3224'
        allowPartiallySucceededBuilds: true
        pipeline: 9
        artifactName: 'icu-$(platform)-$(host)'
        downloadPath: '$(Build.StagingDirectory)'
      displayName: 'Install ICU'
    - template: templates/toolchain.yml
    # - task: MSBuild@1
    #  inputs:
    #    solution: $(Build.SourcesDirectory)\installer\windows-toolchain.wixproj
    #    msbuildArguments: /p:RunWixToolsOutOfProc=true -p:INCLUDE_DEBUG_INFO=INCLUDE_DEBUG_INFO -p:LLVM_BUILD_DIR=$(Build.StagingDirectory)\llvm -p:CLANG_BUILD_DIR=$(Build.StagingDirectory)\llvm -p:LLD_BUILD_DIR=$(Build.StagingDirectory)\llvm -p:LLDB_BUILD_DIR=$(Build.StagingDirectory)\lldb -p:SWIFT_BUILD_DIR=$(Build.StagingDirectory)\swift -p:SWIFT_SOURCE_DIR=$(Build.SourcesDirectory)\swift
    #  displayName: "Build windows-toolchain-amd64.msi"
    # - task: PublishBuildArtifacts@1
    #  inputs:
    #    pathtoPublish: $(Build.SourcesDirectory)\installer\build\windows-toolchain-amd64.msi
    #    artifactName: windows-toolchain-amd64.msi
    #  displayName: "Publish windows-toolchain-amd64.msi"
    # - task: MSBuild@1
    #  inputs:
    #    solution: $(Build.SourcesDirectory)\installer\windows-runtime.wixproj
    #    msbuildArguments: /p:RunWixToolsOutOfProc=true -p:INCLUDE_DEBUG_INFO=INCLUDE_DEBUG_INFO -p:LLVM_BUILD_DIR=$(Build.StagingDirectory)\llvm -p:CLANG_BUILD_DIR=$(Build.StagingDirectory)\llvm -p:LLDB_BUILD_DIR=$(Build.StagingDirectory)\lldb -p:SWIFT_BUILD_DIR=$(Build.StagingDirectory)\swift -p:SWIFT_SOURCE_DIR=$(Build.SourcesDirectory)\swift
    #  displayName: "Build windows-runtime-amd64.msi"
    # - task: PublishBuildArtifacts@1
    #  inputs:
    #    pathtoPublish: $(Build.SourcesDirectory)\installer\build\windows-runtime-amd64.msi
    #    artifactName: windows-runtime-amd64.msi
    #  displayName: "Publish windows-runtime-amd64.msi"
    # - task: MSBuild@1
    #  inputs:
    #    solution: $(Build.SourcesDirectory)\installer\windows-sdk.wixproj
    #    msbuildArguments: /p:RunWixToolsOutOfProc=true -p:INCLUDE_DEBUG_INFO=INCLUDE_DEBUG_INFO -p:LLVM_BUILD_DIR=$(Build.StagingDirectory)\llvm -p:CLANG_BUILD_DIR=$(Build.StagingDirectory)\llvm -p:LLDB_BUILD_DIR=$(Build.StagingDirectory)\lldb -p:SWIFT_BUILD_DIR=$(Build.StagingDirectory)\swift -p:SWIFT_SOURCE_DIR=$(Build.SourcesDirectory)\swift
    #  displayName: "Build windows-sdk.msi"
    # - task: PublishBuildArtifacts@1
    #  inputs:
    #    pathtoPublish: $(Build.SourcesDirectory)\installer\build\windows-sdk.msi
    #    artifactName: windows-sdk.msi
    #  displayName: "Publish windows-sdk.msi"
    - script: |
        echo ##vso[task.setvariable variable=PATH]$(icu.directory)/usr/bin;$(install.directory)\bin;$(Build.StagingDirectory)\swift\libdispatch-prefix\bin;%PATH%;%ProgramFiles%\Git\usr\bin
      displayName: 'Update PATH'
    - task: CMake@1
      inputs:
        cmakeArgs: --build $(Build.StagingDirectory)\swift --target check-swift-validation
      displayName: 'test swift'
      continueOnError: true
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '$(Build.StagingDirectory)/swift/swift-test-results/*/*.xml'
