pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/curl.yml
      - .ci/templates/curl.yml
schedules:
  - cron: "0 8 * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Nightly (8:00 AM) Build"
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/curl.yml
      - .ci/templates/curl.yml
jobs:
  - template: templates/curl.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'

      arch: armv7
      host: arm
      platform: windows

  - template: templates/curl.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'

      arch: aarch64
      host: arm64
      platform: windows

  - template: templates/curl.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'

      arch: x86_64
      host: x64
      platform: windows

  - template: templates/curl.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'

      arch: i686
      host: x86
      platform: windows

  - template: templates/curl.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'

      arch: armv7
      host: arm
      platform: android

  - template: templates/curl.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'

      arch: aarch64
      host: arm64
      platform: android

  - template: templates/curl.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'

      arch: x86_64
      host: x64
      platform: android


  - template: templates/curl.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'

      arch: i686
      host: x86
      platform: android

  - template: templates/curl.yml
    parameters:
      pool:
        vmImage: 'ubuntu-18.04'

      arch: x86_64
      host: x64
      platform: linux

