
trigger:
 branches:
   include:
     - master
 paths:
   include:
     - .ci/graphviz.yml
     - .ci/templates/graphviz.yml

pool:
  vmImage: windows-latest

variables:
  install.directory: $(Build.StagingDirectory)/graphviz-windows-x64/Library/graphviz-development

steps:
  - checkout: self
  - script: |
      git clone --no-tags --depth=1 https://gitlab.com/graphviz/graphviz.git
      git -C graphviz submodule update --init
  - task: BatchScript@1
    inputs:
      filename: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat
      arguments: -no_logo -arch=x64 -host_arch=x64
      modifyEnvironment: true
    displayName: 'VsDevCmd'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.x
    name: python
  - task: CMake@1
    inputs:
      cmakeArgs:
        -B $(Build.BinariesDirectory)/graphviz
        -D BISON_EXECUTABLE=$(Build.SourcesDirectory)/graphviz/windows/dependencies/graphviz-build-utilities/winflexbison/win_bison.exe
        -D FLEX_EXECUTABLE=$(Build.SourcesDirectory)/graphviz/windows/dependencies/graphviz-build-utilities/winflexbison/win_flex.exe
        -D CMAKE_BUILD_TYPE=MinSizeRel
        -D CMAKE_INSTALL_PREFIX=$(install.directory)/usr
        -S $(Build.SourcesDirectory)/graphviz
  - task: CMake@1
    inputs:
      cmakeArgs: --build $(Build.BinariesDirectory)/graphviz --target install
  - publish: $(Build.StagingDirectory)/graphviz-windows-x64
    artifact: graphviz-windows-x64
