pr:
  branches:
    include:
      - trunk
  paths:
    include:
      - .ci/libxml2.yml
      - .ci/templates/libxml2.yml
resources:
  repositories:
    - repository: compnerd/libxml2
      type: github
      name: compnerd/libxml2
      ref: refs/heads/cmake
      endpoint: GitHub
schedules:
  - cron: "0 8 * * *"
    branches:
      include:
        - trunk
    always: true
    displayName: "Nightly (8:00 AM) Build"
trigger:
  branches:
    include:
      - trunk
  paths:
    include:
      - .ci/libxml2.yml
      - .ci/templates/libxml2.yml
stages:
  - stage: android
    dependsOn:
    pool:
      vmImage: 'windows-2019'
    jobs:
      - template: templates/libxml2.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: armv7
          host: arm
          platform: android

      - template: templates/libxml2.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: aarch64
          host: arm64
          platform: android

      - template: templates/libxml2.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: x86_64
          host: x64
          platform: android

      - template: templates/libxml2.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: i686
          host: x86
          platform: android

  - stage: linux
    dependsOn:
    pool:
      vmImage: 'ubuntu-18.04'
    jobs:
      - template: templates/libxml2.yml
        parameters:
          arch: x86_64
          host: x64
          platform: linux

  - stage: windows
    dependsOn:
    pool:
      vmimage: 'windows-2019'
    jobs:
      - template: templates/libxml2.yml
        parameters:
          visualstudio: 2019/enterprise

          arch: armv7
          host: arm
          platform: windows

      - template: templates/libxml2.yml
        parameters:
          visualstudio: 2019/enterprise

          arch: aarch64
          host: arm64
          platform: windows

      - template: templates/libxml2.yml
        parameters:
          visualstudio: 2019/enterprise

          arch: x86_64
          host: x64
          platform: windows

      - template: templates/libxml2.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: i686
          host: x86
          platform: windows
