pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/linux-devtools.yml
      - .ci/templates/linux-devtools.yml
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/linux-devtools.yml
      - .ci/templates/linux-devtools.yml
jobs:
  - job: linux_x64
    pool: FlowKey
    variables:
      arch: x86_64
      host: x64
      platform: linux

      sqlite.directory: $(Pipeline.Workspace)/Library/sqlite-3.30.1

      toolchain.version: development
      toolchain.directory: $(Pipeline.Workspace)/Library/Developer/Toolchains/unknown-Asserts-$(toolchain.version).xctoolchain

      platform.directory: $(Build.StagingDirectory)/Library/Developer/Platforms/Linux.platform

      llbuild.version: development
      tsc.version: development
      IndexStoreDB.version: development
      SwiftPM.version: development
    steps:
    - template: templates/linux-devtools.yml
