name: 'Linux DevTools'
pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/linux-devtools.yml
      - .ci/templates/linux-devtools.yml
schedules:
  - cron: "0 8 * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Nightly (8:00 AM) Build"
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/linux-devtools.yml
      - .ci/templates/linux-devtools.yml
jobs:
  - job: linux_x64
    pool: FlowKey
    variables:
      arch: x86_64
      host: x64
      platform: linux

      sqlite.version: 3.28.0
      sqlite.directory: $(System.ArtifactsDirectory)/sqlite-$(platform)-$(host)/sqlite-$(sqlite.version)

      toolchain.version: development
      toolchain.directory: $(System.ArtifactsDirectory)/toolchain/Developer/Toolchains/unknown-Asserts-$(toolchain.version).xctoolchain

      platform.directory: $(Build.StagingDirectory)/Library/Developer/Platforms/Linux.platform

      llbuild.version: development
    steps:
    - script: |
        echo "##vso[task.setvariable variable=PATH]$(toolchain.directory)/usr/bin;%PATH%"
      displayName: 'Update PATH'
    - template: templates/linux-devtools.yml
