pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/linux-devtools.yml
      - .ci/templates/linux-devtools.yml
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/linux-devtools.yml
      - .ci/templates/linux-devtools.yml
jobs:
  - template: templates/linux-devtools.yml
    parameters:
      pool: FlowKey

      arch: x86_64
      host: x64
      platform: linux
