pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/linux-sdk.yml
      - .ci/templates/linux-sdk.yml
      - cmake/caches/linux-x86_64.cmake
      - cmake/caches/linux-x86_64-swift-flags.cmake
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/linux-sdk.yml
      - .ci/templates/linux-sdk.yml
      - cmake/caches/linux-x86_64.cmake
      - cmake/caches/linux-x86_64-swift-flags.cmake
jobs:
  - template: templates/linux-sdk.yml
    parameters:
      pool: FlowKey

      arch: x86_64
      host: x64
      platform: linux

      triple: x86_64-unknown-linux-gnu
