pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/toolchain-linux-x64.yml
      - .ci/templates/toolchain.yml
      - .ci/templates/linux-devtools.yml
      - .ci/templates/linux-sdk.yml
      - cmake/caches/org.compnerd.dt.cmake
      - cmake/caches/linux-x86_64.cmake
      - cmake/caches/linux-x86_64-swift-flags.cmake
resources:
  pipelines:
    - pipeline: icu
      source: 'Dependencies/ICU'
    - pipeline: xml2
      source: 'Dependencies/XML2'
    - pipeline: curl
      source: 'Dependencies/CURL'
    - pipeline: zlib
      source: 'Dependencies/zlib'
  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: refs/heads/swift/master
      endpoint: GitHub
    - repository: apple/swift-cmark
      type: github
      name: apple/swift-cmark
      endpoint: GitHub
    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      endpoint: GitHub
    - repository: apple/swift
      type: github
      name: apple/swift
      endpoint: GitHub
    - repository: apple/swift-corelibs-foundation
      type: github
      name: apple/swift-corelibs-foundation
      endpoint: GitHub
    - repository: apple/swift-corelibs-xctest
      type: github
      name: apple/swift-corelibs-xctest
      endpoint: GitHub
schedules:
  - cron: "0 * * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Hourly Build"
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/toolchain-linux-x64.yml
      - .ci/templates/toolchain.yml
      - .ci/templates/linux-devtools.yml
      - .ci/templates/linux-sdk.yml
      - cmake/caches/org.compnerd.dt.cmake
      - cmake/caches/linux-x86_64.cmake
      - cmake/caches/linux-x86_64-swift-flags.cmake
stages:
  - stage: toolchain
    jobs:
      - template: templates/toolchain.yml
        parameters:
          pool: FlowKey

          arch: x86_64
          host: x64
          platform: linux

          triple: x86_64-unknown-linux-gnu

          SWIFT_OPTIONS: -DSWIFT_LINUX_x86_64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_LINUX_x86_64_ICU_UC=$(icu.directory)/usr/lib/libicuuc$(icu.version).so -DSWIFT_LINUX_x86_64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_LINUX_x86_64_ICU_I18N=$(icu.directory)/usr/lib/libicuin$(icu.version).so -DSWIFT_BUILD_DYNAMIC_STDLIB=YES -DSWIFT_BUILD_DYNAMIC_SDK_OVERLAY=YES

  - stage: sdk
    jobs:
      - template: templates/linux-sdk.yml
        parameters:
          pool: FlowKey

          arch: x86_64
          host: x64
          platform: linux

          triple: x86_64-unknown-linux-gnu

  - stage: devtools
    jobs:
      - template: templates/linux-devtools.yml
        parameters:
          pool: FlowKey

          arch: x86_64
          host: x64
          platform: linux
