pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/toolchain-vs2019-amd64-msi.yml
      - wix/windows-toolchain.wixproj
      - wix/windows-toolchain.wxs
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/toolchain-vs2019-amd64-msi.yml
      - wix/windows-toolchain.wixproj
      - wix/windows-toolchain.wxs
jobs:
  - job: windows_x64
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: BatchScript@1
        inputs:
          filename: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat
          arguments: -no_logo -arch=x64 -host_arch=x64
          modifyEnvironment: true
        displayName: 'vcvarsall.bat'
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'specific'
          project: '3133d6ab-80a8-4996-ac4f-03df25cd3224'
          definition: '7'
          specificBuildWithTriggering: true
          buildVersionToDownload: 'latest'
          allowPartiallySucceededBuilds: true
          allowFailedBuilds: true
          artifactName: 'toolchain-windows-x64'
          targetPath: '$(System.ArtifactsDirectory)'
        displayName: 'install toolchain'
      - task: MSBuild@1
        inputs:
          solution: $(Build.SourcesDirectory)\wix\windows-toolchain.wixproj
          msbuildArguments: /p:RunWixToolsOutOfProc=true -p:ARCH=amd64 -p:TOOLCHAIN_ROOT=$(System.ArtifactsDirectory)/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain
        displayName: 'Build windows-toolchain-amd64.msi'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)\wix\build\windows-toolchain-amd64.msi'
          ArtifactName: 'windows-toolchain-amd64.msi'
        displayName: "Publish windows-toolchain-amd64.msi"


