pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/toolchain-vs2017-amd64-facebook.yml
      - .ci/templates/toolchain.yml
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/toolchain-vs2017-amd64-facebook.yml
      - .ci/templates/toolchain.yml
resources:
  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: refs/heads/swift/master
      endpoint: GitHub
    - repository: apple/swift-cmark
      type: github
      name: apple/swift-cmark
      endpoint: GitHub
    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      endpoint: GitHub
    - repository: apple/swift
      type: github
      name: apple/swift
      endpoint: GitHub
schedules:
- cron: "0 */3 * * *"
  displayName: "O'clock builds"
  branches:
    include:
    - master
  always: true
- cron: "30 1-22/3 * * *"
  displayName: "Half past builds"
  branches:
    include:
    - master
  always: true
jobs:
  - template: templates/toolchain.yml
    parameters:
      VisualStudio: 2017/Community
      pool: Facebook-VS2017
      tests: true

      arch: x86_64
      host: x64
      platform: windows

      triple: x86_64-unknown-windows-msvc

      LLVM_OPTIONS: -DLLVM_PARALLEL_LINK_JOBS=2 -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe
      LLDB_OPTIONS: -DLLDB_DISABLE_PYTHON=YES
      SWIFT_OPTIONS: -DSWIFT_WINDOWS_x86_64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_x86_64_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_x86_64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_x86_64_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DSWIFT_PARALLEL_LINK_JOBS=8 -DSWIFT_BUILD_DYNAMIC_STDLIB=YES -DSWIFT_BUILD_DYNAMIC_SDK_OVERLAY=YES
