pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/toolchain-vs2019-arm64.yml
      - .ci/templates/toolchain.yml
resources:
  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: refs/heads/swift/master
      endpoint: GitHub
    - repository: apple/swift-cmark
      type: github
      name: apple/swift-cmark
      endpoint: GitHub
    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      endpoint: GitHub
    - repository: apple/swift
      type: github
      name: apple/swift
      endpoint: GitHub
schedules:
  - cron: "0 0 * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Daily Build"
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/toolchain-vs2019-arm64.yml
      - .ci/templates/toolchain.yml
jobs:
  - template: templates/toolchain.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'

      arch: aarch64
      host: arm64
      platform: windows

      triple: aarch64-unknown-windows-msvc

      # NOTE(compnerd) DIA does not contain ARM64 diaguids.lib
      LLVM_OPTIONS: -DLLVM_ENABLE_DIA_SDK=NO -DLLVM_INCLUDE_TESTS=NO -DCLANG_INCLUDE_TESTS=NO -DLLD_INCLUDE_TESTS=NO
      LLDB_OPTIONS: -DLLDB_DISABLE_PYTHON=YES -DLLDB_INCLUDE_TESTS=NO
      SWIFT_OPTIONS: -DSWIFT_INCLUDE_TESTS=NO -DSWIFT_ENABLE_SOURCEKIT_TESTS=NO
