pr:
  branches:
    include:
      - trunk
  paths:
    include:
      - .ci/vs2019-swift-5.3.yml
      - .ci/templates/toolchain.yml

resources:
  pipelines:
    - pipeline: icu
      source: ICU

    - pipeline: xml2
      source: XML2

    - pipeline: curl
      source: CURL

    - pipeline: zlib
      source: zlib

    - pipeline: sqlite
      source: SQLite

  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: swift/release/5.3
      endpoint: GitHub

    - repository: apple/swift
      type: github
      name: apple/swift
      ref: release/5.3
      endpoint: GitHub

    - repository: apple/swift-cmark
      type: github
      name: apple/swift-cmark
      ref: release/5.3
      endpoint: GitHub

    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      ref: release/5.3
      endpoint: GitHub

    - repository: apple/swift-corelibs-foundation
      type: github
      name: apple/swift-corelibs-foundation
      ref: release/5.3
      endpoint: GitHub

    - repository: apple/swift-corelibs-xctest
      type: github
      name: apple/swift-corelibs-xctest
      ref: release/5.3
      endpoint: GitHub

    - repository: apple/swift-llbuild
      type: github
      name: apple/swift-llbuild
      ref: release/5.3
      endpoint: GitHub

    - repository: apple/swift-tools-support-core
      type: github
      name: apple/swift-tools-support-core
      ref: release/5.3
      endpoint: GitHub

    - repository: apple/swift-package-manager
      type: github
      name: apple/swift-package-manager
      ref: release/5.3
      endpoint: GitHub

    - repository: apple/indexstore-db
      type: github
      name: apple/indexstore-db
      ref: release/5.3
      endpoint: GitHub

    - repository: apple/sourcekit-lsp
      type: github
      name: apple/sourcekit-lsp
      ref: release/5.3
      endpoint: GitHub

    - repository: tensorflow/swift-apis
      type: github
      name: tensorflow/swift-apis
      ref: master
      endpoint: GitHub

    - repository: pvieito/PythonKit
      type: github
      name: pvieito/PythonKit
      ref: master
      endpoint: GitHub

    - repository: jpsim/Yams
      type: github
      name: jpsim/Yams
      ref: master
      endpoint: GitHub

    - repository: apple/swift-driver
      type: github
      name: apple/swift-driver
      ref: main
      endpoint: GitHub

    - repository: apple/swift-argument-parser
      type: github
      name: apple/swift-argument-parser
      ref: main
      endpoint: GitHub

schedules:
  - cron: "0 23 * * *"
    branches:
      include:
        - trunk
    always: true
    displayName: "Daily (5:00 PM) Build"

trigger:
  branches:
    include:
      - trunk
  paths:
    include:
      - .ci/vs2019-swift-5.3.yml
      - .ci/templates/toolchain.yml

stages:
  - stage: toolchain
    pool:
      vmImage: 'windows-2019'
    jobs:
      - template: templates/toolchain.yml
        parameters:
          VisualStudio: 2019/Enterprise
          PythonVersion: 2.7.x

          arch: x86_64
          host: x64
          platform: windows

          triple: x86_64-unknown-windows-msvc

          ICU_VERSION: 67
          LLVM_OPTIONS: -DLLVM_ENABLE_LIBEDIT=NO -DLLVM_PARALLEL_LINK_JOBS=2 -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe -DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-windows-msvc
          SWIFT_OPTIONS: -DSWIFT_WINDOWS_x86_64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_x86_64_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_x86_64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_x86_64_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DSWIFT_PARALLEL_LINK_JOBS=2 -DSWIFT_BUILD_DYNAMIC_STDLIB=YES -DSWIFT_BUILD_DYNAMIC_SDK_OVERLAY=YES

          RUN_TESTS: true
          RUN_VALIDATION_TESTS: false

          VERSION: 5.3

  - stage: windows_sdk
    dependsOn: toolchain
    displayName: 'Windows SDK'
    pool:
      vmImage: 'windows-2019'
    jobs:
      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2019/Enterprise
          PythonVersion: 2.7.x

          arch: armv7
          host: arm
          platform: windows

          triple: armv7-unknown-windows-msvc

          os: Windows
          proc: arm

          ICU_VERSION: 67
          SWIFT_OPTIONS: -DSWIFT_WINDOWS_armv7_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_armv7_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_armv7_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_armv7_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe

          VERSION: 5.3

      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2019/Enterprise
          PythonVersion: 2.7.x

          arch: aarch64
          host: arm64
          platform: windows

          triple: aarch64-unknown-windows-msvc

          os: Windows
          proc: arm64

          ICU_VERSION: 67
          SWIFT_OPTIONS: -DSWIFT_WINDOWS_aarch64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_aarch64_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_aarch64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_aarch64_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe

          VERSION: 5.3

      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2019/Enterprise
          PythonVersion: 2.7.x

          arch: x86_64
          host: x64
          platform: windows

          triple: x86_64-unknown-windows-msvc

          os: Windows
          proc: amd64

          ICU_VERSION: 67
          SWIFT_OPTIONS: -DSWIFT_WINDOWS_x86_64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_x86_64_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_x86_64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_x86_64_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe

          VERSION: 5.3

      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2019/Enterprise
          PythonVersion: 2.7.x

          arch: i686
          host: x86
          platform: windows

          triple: i686-unknown-windows-msvc

          os: Windows
          proc: i686

          ICU_VERSION: 67
          SWIFT_OPTIONS: -DSWIFT_WINDOWS_i686_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_i686_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_i686_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_i686_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe

          VERSION: 5.3

  - stage: package_toolchain
    dependsOn: toolchain
    displayName: package Toolchain
    pool:
      vmImage: 'windows-2019'
    jobs:
      - template: templates/toolchain-msi.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: x86_64
          host: x64
          platform: windows

          os: Windows
          proc: amd64

          VERSION: 5.3

  - stage: package_windows_sdk
    dependsOn: windows_sdk
    displayName: package SDK
    pool:
      vmImage: 'windows-2019'
    jobs:
      - template: templates/sdk-msi.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: x86_64
          host: x64
          platform: windows

          os: Windows
          proc: amd64

          VERSION: 5.3

  - stage: package_icu
    dependsOn: []
    displayName: package ICU
    pool:
      vmImage: 'windows-2019'
    jobs:
      - template: templates/icu-msi.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: x86_64
          host: x64
          platform: windows

          os: Windows
          proc: amd64

          VERSION: 5.3

  - stage: package_installer
    dependsOn:
      - package_toolchain
      - package_windows_sdk
      - package_icu
    displayName: package Installer
    pool:
      vmImage: 'windows-2019'
    jobs:
      - template: templates/swift-installer-bundle.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: x86_64
          host: x64
          platform: windows

          os: Windows
          proc: amd64

          VERSION: 5.3
