schedules:
  - cron: "0 */6 * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Automated Build"

resources:
  pipelines:
    - pipeline: sqlite
      source: SQLite

    - pipeline: icu
      source: ICU

  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: swift/main
      endpoint: GitHub

    - repository: apple/swift
      type: github
      name: apple/swift
      ref: main
      endpoint: GitHub

    - repository: apple/swift-cmark
      type: github
      name: apple/swift-cmark
      ref: main
      endpoint: GitHub

    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      ref: main
      endpoint: GitHub

    - repository: apple/swift-corelibs-foundation
      type: github
      name: apple/swift-corelibs-foundation
      ref: main
      endpoint: GitHub

    - repository: apple/swift-corelibs-xctest
      type: github
      name: apple/swift-corelibs-xctest
      ref: main
      endpoint: GitHub

    - repository: apple/swift-llbuild
      type: github
      name: apple/swift-llbuild
      ref: main
      endpoint: GitHub

    - repository: apple/swift-tools-support-core
      type: github
      name: apple/swift-tools-support-core
      ref: main
      endpoint: GitHub

    - repository: apple/swift-package-manager
      type: github
      name: apple/swift-package-manager
      ref: main
      endpoint: GitHub

    - repository: apple/indexstore-db
      type: github
      name: apple/indexstore-db
      ref: main
      endpoint: GitHub

    - repository: apple/sourcekit-lsp
      type: github
      name: apple/sourcekit-lsp
      ref: main
      endpoint: GitHub

    - repository: jpsim/Yams
      type: github
      name: jpsim/Yams
      ref: main
      endpoint: GitHub

    - repository: apple/swift-driver
      type: github
      name: apple/swift-driver
      ref: main
      endpoint: GitHub

    - repository: apple/swift-argument-parser
      type: github
      name: apple/swift-argument-parser
      ref: main
      endpoint: GitHub

    - repository: apple/swift-crypto
      type: github
      name: apple/swift-crypto
      ref: refs/tags/1.1.5
      endpoint: GitHub

    - repository: apple/swift-collections
      type: github
      name: apple/swift-collections
      ref: main
      endpoint: GitHub

    - repository: apple/swift-system
      type: github
      name: apple/swift-system
      ref: main
      endpoint: GitHub

stages:
- stage: devtools
  pool: Google
  jobs:
    - template: templates/windows-devtools.yml
      parameters:
        VisualStudio: 2019/Community

        arch: aarch64
        host: arm64
        platform: windows

        os: Windows
        proc: arm64

        ICU_VERSION: 67
        SQLITE_VERSION: 3.34.0
        USE_PREBUILT_TOOLCHAIN: true

    - template: templates/windows-devtools.yml
      parameters:
        VisualStudio: 2019/Community

        arch: x86_64
        host: x64
        platform: windows

        os: Windows
        proc: amd64

        ICU_VERSION: 67
        SQLITE_VERSION: 3.34.0
        USE_PREBUILT_TOOLCHAIN: true
