pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/vs2017-facebook.yml
      - .ci/templates/toolchain.yml
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/vs2017-facebook.yml
      - .ci/templates/toolchain.yml
resources:
  pipelines:
    - pipeline: icu
      source: 'ICU'
    - pipeline: xml2
      source: 'XML2'
    - pipeline: curl
      source: 'CURL'
    - pipeline: zlib
      source: 'zlib'
  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: swift/master
      endpoint: GitHub
    - repository: apple/swift
      type: github
      name: apple/swift
      ref: master
      endpoint: GitHub
    - repository: apple/swift-cmark
      type: github
      name: apple/swift-cmark
      ref: master
      endpoint: GitHub
    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      ref: master
      endpoint: GitHub
    - repository: apple/swift-corelibs-foundation
      type: github
      name: apple/swift-corelibs-foundation
      ref: master
      endpoint: GitHub
    - repository: apple/swift-corelibs-xctest
      type: github
      name: apple/swift-corelibs-xctest
      ref: master
      endpoint: GitHub
    - repository: tensorflow/swift-apis
      type: github
      name: tensorflow/swift-apis
      ref: master
      endpoint: GitHub
schedules:
- cron: "0 */2 * * *"
  displayName: "Toolchain builds"
  branches:
    include:
    - master
  always: true
stages:
  - stage: toolchain
    pool: Facebook-VS2017
    jobs:
      - template: templates/toolchain.yml
        parameters:
          VisualStudio: 2017/Community
          tests: true

          arch: x86_64
          host: x64
          platform: windows

          triple: x86_64-unknown-windows-msvc

          LLVM_OPTIONS: -DLLVM_ENABLE_LIBEDIT=NO -DLLVM_PARALLEL_LINK_JOBS=2 -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe
          LLDB_OPTIONS: -DLLDB_DISABLE_PYTHON=YES
          SWIFT_OPTIONS: -DSWIFT_WINDOWS_x86_64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_x86_64_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_x86_64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_x86_64_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DSWIFT_PARALLEL_LINK_JOBS=8 -DSWIFT_BUILD_DYNAMIC_STDLIB=YES -DSWIFT_BUILD_DYNAMIC_SDK_OVERLAY=YES

  - stage: sdk
    pool: Facebook-VS2017
    jobs:
      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2017/Community

          arch: armv7
          host: arm
          platform: windows

          triple: armv7-unknown-windows-msvc

          SWIFT_OPTIONS: -DSWIFT_WINDOWS_armv7_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_armv7_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_armv7_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_armv7_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe

      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2017/Community

          arch: aarch64
          host: arm64
          platform: windows

          triple: aarch64-unknown-windows-msvc

          SWIFT_OPTIONS: -DSWIFT_WINDOWS_aarch64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_aarch64_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_aarch64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_aarch64_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe

      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2017/Community

          arch: x86_64
          host: x64
          platform: windows

          triple: x86_64-unknown-windows-msvc

          SWIFT_OPTIONS: -DSWIFT_WINDOWS_x86_64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_x86_64_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_x86_64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_x86_64_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe

      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2017/Community

          arch: i686
          host: x86
          platform: windows

          triple: i686-unknown-windows-msvc

          SWIFT_OPTIONS: -DSWIFT_WINDOWS_i686_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_i686_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_i686_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_i686_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe
