
resources:
  pipelines:
    - pipeline: sqlite
      source: SQLite

    - pipeline: icu
      source: ICU

  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: swift/main
      endpoint: GitHub

    - repository: apple/swift
      type: github
      name: apple/swift
      ref: main
      endpoint: GitHub

    - repository: apple/swift-cmark
      type: github
      name: apple/swift-cmark
      ref: main
      endpoint: GitHub

    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      ref: main
      endpoint: GitHub

    - repository: apple/swift-corelibs-foundation
      type: github
      name: apple/swift-corelibs-foundation
      ref: main
      endpoint: GitHub

    - repository: apple/swift-corelibs-xctest
      type: github
      name: apple/swift-corelibs-xctest
      ref: main
      endpoint: GitHub

    - repository: apple/swift-llbuild
      type: github
      name: apple/swift-llbuild
      ref: main
      endpoint: GitHub

    - repository: apple/swift-tools-support-core
      type: github
      name: apple/swift-tools-support-core
      ref: main
      endpoint: GitHub

    - repository: apple/swift-package-manager
      type: github
      name: apple/swift-package-manager
      ref: main
      endpoint: GitHub

    - repository: apple/indexstore-db
      type: github
      name: apple/indexstore-db
      ref: main
      endpoint: GitHub

    - repository: apple/sourcekit-lsp
      type: github
      name: apple/sourcekit-lsp
      ref: main
      endpoint: GitHub

    - repository: jpsim/Yams
      type: github
      name: jpsim/Yams
      ref: main
      endpoint: GitHub

    - repository: apple/swift-driver
      type: github
      name: apple/swift-driver
      ref: main
      endpoint: GitHub

    - repository: apple/swift-argument-parser
      type: github
      name: apple/swift-argument-parser
      ref: main
      endpoint: GitHub

    - repository: apple/swift-crypto
      type: github
      name: apple/swift-crypto
      ref: main
      endpoint: GitHub

stages:
- stage: ICU
  dependsOn: []
  pool: Google
  jobs:
    - template: templates/icu-msi.yml
      parameters:
        VisualStudio: 2019/Community

        arch: aarch64
        host: arm64
        platform: windows

        os: Windows
        proc: arm64

        ICU_VERSION: 67
        USE_PREBUILT_TOOLCHAIN: true

    - template: templates/icu-msi.yml
      parameters:
        VisualStudio: 2019/Community

        arch: x86_64
        host: x64
        platform: windows

        os: Windows
        proc: amd64

        ICU_VERSION: 67
        USE_PREBUILT_TOOLCHAIN: true

- stage: Toolchain
  dependsOn: []
  pool: Google
  jobs:
    - template: templates/toolchain-msi.yml
      parameters:
        VisualStudio: 2019/Community

        arch: aarch64
        host: arm64
        platform: windows

        os: Windows
        proc: arm64

        ICU_VERSION: 67
        USE_PREBUILT_TOOLCHAIN: true

    - template: templates/toolchain-msi.yml
      parameters:
        VisualStudio: 2019/Community

        arch: x86_64
        host: x64
        platform: windows

        os: Windows
        proc: amd64

        ICU_VERSION: 67
        USE_PREBUILT_TOOLCHAIN: true

- stage: SDK
  dependsOn: []
  pool: Google
  jobs:
    - template: templates/sdk-msi.yml
      parameters:
        VisualStudio: 2019/Community

        arch: aarch64
        host: arm64
        platform: windows

        os: Windows
        proc: arm64

        ICU_VERSION: 67
        USE_PREBUILT_TOOLCHAIN: true

    - template: templates/sdk-msi.yml
      parameters:
        VisualStudio: 2019/Community

        arch: x86_64
        host: x64
        platform: windows

        os: Windows
        proc: amd64

        ICU_VERSION: 67
        USE_PREBUILT_TOOLCHAIN: true

- stage: DevTools
  dependsOn: []
  pool: Google
  jobs:
    - template: templates/devtools-msi.yml
      parameters:
        VisualStudio: 2019/Community

        arch: aarch64
        host: arm64
        platform: windows

        os: Windows
        proc: arm64

        ICU_VERSION: 67
        USE_PREBUILT_TOOLCHAIN: true

    - template: templates/devtools-msi.yml
      parameters:
        VisualStudio: 2019/Community

        arch: x86_64
        host: x64
        platform: windows

        os: Windows
        proc: amd64

        ICU_VERSION: 67
        USE_PREBUILT_TOOLCHAIN: true


- stage: Installer
  pool: Google
  dependsOn:
    - ICU
    - Toolchain
    - SDK
    - DevTools
  jobs:
    - template: templates/swift-installer-bundle.yml
      parameters:
        VisualStudio: 2019/Community

        arch: aarch64
        host: arm64
        platform: windows

        os: Windows
        proc: arm64

        ICU_VERSION: 67
        USE_PREBUILT_TOOLCHAIN: true

    - template: templates/swift-installer-bundle.yml
      parameters:
        VisualStudio: 2019/Community

        arch: x86_64
        host: x64
        platform: windows

        os: Windows
        proc: amd64

        ICU_VERSION: 67
        DEVTOOLS: true
        USE_PREBUILT_TOOLCHAIN: true
