pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/vs2019-swift-5.2.yml
      - .ci/templates/toolchain.yml
resources:
  pipelines:
    - pipeline: icu
      source: 'ICU'
    - pipeline: xml2
      source: 'XML2'
    - pipeline: curl
      source: 'CURL'
    - pipeline: zlib
      source: 'zlib'
  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: swift/swift-5.2-branch
      endpoint: GitHub
    - repository: apple/swift
      type: github
      name: apple/swift
      ref: swift-5.2-branch
      endpoint: GitHub
    - repository: apple/swift-cmark
      type: github
      name: apple/swift-cmark
      ref: swift-5.2-branch
      endpoint: GitHub
    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      ref: swift-5.2-branch
      endpoint: GitHub
    - repository: apple/swift-corelibs-foundation
      type: github
      name: apple/swift-corelibs-foundation
      ref: swift-5.2-branch
      endpoint: GitHub
    - repository: apple/swift-corelibs-xctest
      type: github
      name: apple/swift-corelibs-xctest
      ref: swift-5.2-branch
      endpoint: GitHub
    - repository: tensorflow/swift-apis
      type: github
      name: tensorflow/swift-apis
      ref: master
      endpoint: GitHub
schedules:
  - cron: "0 17 * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Daily (5:00 PM) Build"
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/vs2019-swift-5.2.yml
      - .ci/templates/toolchain.yml
stages:
  - stage: toolchain
    pool:
      vmImage: 'windows-2019'
    jobs:
      - template: templates/toolchain.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: aarch64
          host: arm64
          platform: windows

          triple: aarch64-unknown-windows-msvc

          # NOTE(compnerd) DIA does not contain ARM64 diaguids.lib
          LLVM_OPTIONS: -DLLVM_ENABLE_LIBEDIT=NO -DLLVM_ENABLE_DIA_SDK=NO -DLLVM_INCLUDE_TESTS=NO -DCLANG_INCLUDE_TESTS=NO -DLLD_INCLUDE_TESTS=NO
          LLDB_OPTIONS: -DLLDB_DISABLE_PYTHON=YES -DLLDB_INCLUDE_TESTS=NO
          # NOTE(compnerd) cannot build SyntaxParserLib and SourceKit due to
          # libdispatch's dependency on clang
          SWIFT_OPTIONS: -DSWIFT_INCLUDE_TESTS=NO -DSWIFT_ENABLE_SOURCEKIT_TESTS=NO -DSWIFT_BUILD_SYNTAXPARSERLIB=NO -DSWIFT_BUILD_SOURCEKIT=NO

      - template: templates/toolchain.yml
        parameters:
          VisualStudio: 2019/Enterprise
          tests: true

          arch: x86_64
          host: x64
          platform: windows

          triple: x86_64-unknown-windows-msvc

          LLVM_OPTIONS: -DLLVM_ENABLE_LIBEDIT=NO -DLLVM_PARALLEL_LINK_JOBS=2 -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe
          LLDB_OPTIONS: -DLLDB_DISABLE_PYTHON=YES
          SWIFT_OPTIONS: -DSWIFT_WINDOWS_x86_64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_x86_64_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_x86_64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_x86_64_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DSWIFT_PARALLEL_LINK_JOBS=2 -DSWIFT_BUILD_DYNAMIC_STDLIB=YES -DSWIFT_BUILD_DYNAMIC_SDK_OVERLAY=YES

  - stage: android_sdk
    dependsOn: toolchain
    displayName: 'Android SDK'
    pool:
      vmImage: 'windows-2019'
    jobs:
      - template: templates/android-sdk.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: armv7
          host: arm
          platform: android

          triple: armv7-unknown-linux-androideabi

      - template: templates/android-sdk.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: aarch64
          host: arm64
          platform: android

          triple: aarch64-unknown-linux-android

      - template: templates/android-sdk.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: x86_64
          host: x64
          platform: android

          triple: x86_64-unknown-linux-android

      - template: templates/android-sdk.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: i686
          host: x86
          platform: android

          triple: i686-unknown-linux-android

  - stage: windows_sdk
    dependsOn: toolchain
    displayName: 'Windows SDK'
    pool:
      vmImage: 'windows-2019'
    jobs:
      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: armv7
          host: arm
          platform: windows

          triple: armv7-unknown-windows-msvc

          SWIFT_OPTIONS: -DSWIFT_WINDOWS_armv7_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_armv7_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_armv7_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_armv7_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe

      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: aarch64
          host: arm64
          platform: windows

          triple: aarch64-unknown-windows-msvc

          SWIFT_OPTIONS: -DSWIFT_WINDOWS_aarch64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_aarch64_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_aarch64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_aarch64_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe

      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: x86_64
          host: x64
          platform: windows

          triple: x86_64-unknown-windows-msvc

          SWIFT_OPTIONS: -DSWIFT_WINDOWS_x86_64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_x86_64_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_x86_64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_x86_64_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe

      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: i686
          host: x86
          platform: windows

          triple: i686-unknown-windows-msvc

          SWIFT_OPTIONS: -DSWIFT_WINDOWS_i686_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_i686_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_i686_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_i686_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=$(python.pythonLocation)/python.exe
