pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/windows-sdk-facebook-vs2019.yml
      - .ci/templates/windows-sdk.yml
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/windows-sdk-facebook-vs2019.yml
      - .ci/templates/windows-sdk.yml
resources:
  pipelines:
  - pipeline: toolchain
    source: 'Development\Facebook\VS2019/Toolchain for Windows x64'
    trigger:
      branches:
        include:
        - master
jobs:
  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2019/Community
      pool: Facebook-VS2019
      branch: master
      toolchain: 31

      arch: 'armv7'
      host: 'arm'
      triple: 'armv7-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2019/Community
      pool: Facebook-VS2019
      branch: master
      toolchain: 31

      arch: 'aarch64'
      host: 'arm64'
      triple: 'aarch64-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2019/Community
      pool: Facebook-VS2019
      branch: master
      toolchain: 31

      arch: 'x86_64'
      host: 'x64'
      triple: 'x86_64-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2019/Community
      pool: Facebook-VS2019
      branch: master
      toolchain: 31

      arch: 'i686'
      host: 'x86'
      triple: 'i686-unknown-windows-msvc'
