pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/windows-sdk-facebook-vs2017.yml
      - .ci/templates/windows-sdk.yml
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/windows-sdk-facebook-vs2017.yml
      - .ci/templates/windows-sdk.yml
jobs:
  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2017/Community
      pool: Facebook-VS2017
      branch: master
      toolchain: 5

      arch: 'armv7'
      host: 'arm'
      triple: 'armv7-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2017/Community
      pool: Facebook-VS2017
      branch: master
      toolchain: 5

      arch: 'aarch64'
      host: 'arm64'
      triple: 'aarch64-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2017/Community
      pool: Facebook-VS2017
      branch: master
      toolchain: 5

      arch: 'x86_64'
      host: 'x64'
      triple: 'x86_64-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2017/Community
      pool: Facebook-VS2017
      branch: master
      toolchain: 5

      arch: 'i686'
      host: 'x86'
      triple: 'i686-unknown-windows-msvc'

