pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/windows-devtools.yml
      - .ci/templates/windows-devtools.yml
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/windows-devtools.yml
      - .ci/templates/windows-devtools.yml
jobs:
  - template: templates/windows-devtools.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'
      branch: master
      toolchain: 7
      sdk: 2

      arch: 'aarch64'
      host: 'arm64'

  - template: templates/windows-devtools.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'
      branch: master
      toolchain: 7
      sdk: 2

      arch: 'x86_64'
      host: 'x64'
