pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/windows-sdk-5.2.yml
      - .ci/templates/windows-sdk.yml
resources:
  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: refs/heads/swift/swift-5.2-branch
      endpoint: GitHub
    - repository: apple/swift-cmark
      type: github
      name: apple/swift-cmark
      ref: refs/heads/swift-5.2-branch
      endpoint: GitHub
    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      ref: refs/heads/swift-5.2-branch
      endpoint: GitHub
    - repository: apple/swift
      type: github
      name: apple/swift
      ref: refs/heads/swift-5.2-branch
      endpoint: GitHub
    - repository: apple/swift-corelibs-foundation
      type: github
      name: apple/swift-corelibs-foundation
      ref: refs/heads/swift-5.2-branch
      endpoint: GitHub
    - repository: apple/swift-corelibs-xctest
      type: github
      name: apple/swift-corelibs-xctest
      ref: refs/heads/swift-5.2-branch
      endpoint: GitHub
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/windows-sdk-5.2.yml
      - .ci/templates/windows-sdk.yml
jobs:
  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'
      toolchain: 30

      arch: 'armv7'
      host: 'arm'
      triple: 'armv7-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'
      toolchain: 30

      arch: 'aarch64'
      host: 'arm64'
      triple: 'aarch64-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'
      toolchain: 30

      arch: 'x86_64'
      host: 'x64'
      triple: 'x86_64-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'
      toolchain: 30

      arch: 'i686'
      host: 'x86'
      triple: 'i686-unknown-windows-msvc'
