pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/windows-sdk-facebook-vs2017.yml
      - .ci/templates/windows-sdk.yml
resources:
  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: refs/heads/swift/master
      endpoint: GitHub
    - repository: apple/swift-cmark
      type: github
      name: apple/swift-cmark
      ref: refs/heads/master
      endpoint: GitHub
    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      ref: refs/heads/master
      endpoint: GitHub
    - repository: apple/swift
      type: github
      name: apple/swift
      ref: refs/heads/master
      endpoint: GitHub
    - repository: apple/swift-corelibs-foundation
      type: github
      name: apple/swift-corelibs-foundation
      ref: refs/heads/master
      endpoint: GitHub
    - repository: apple/swift-corelibs-xctest
      type: github
      name: apple/swift-corelibs-xctest
      ref: refs/heads/master
      endpoint: GitHub
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/windows-sdk-facebook-vs2017.yml
      - .ci/templates/windows-sdk.yml
resources:
  pipelines:
  - pipeline: toolchain
    source: 'Development\Facebook\VS2017/Toolchain for Windows x64'
    trigger:
      branches:
        include:
        - master
jobs:
  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2017/Community
      pool: Facebook-VS2017
      toolchain: 5

      arch: 'armv7'
      host: 'arm'
      triple: 'armv7-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2017/Community
      pool: Facebook-VS2017
      toolchain: 5

      arch: 'aarch64'
      host: 'arm64'
      triple: 'aarch64-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2017/Community
      pool: Facebook-VS2017
      toolchain: 5

      arch: 'x86_64'
      host: 'x64'
      triple: 'x86_64-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2017/Community
      pool: Facebook-VS2017
      toolchain: 5

      arch: 'i686'
      host: 'x86'
      triple: 'i686-unknown-windows-msvc'
