pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/windows-sdk.yml
      - .ci/templates/windows-sdk.yml
      - cmake/caches/Windows-aarch64-clang.cmake
      - cmake/caches/Windows-aarch64-swift-flags.cmake
      - cmake/caches/Windows-armv7-clang.cmake
      - cmake/caches/Windows-armv7-swift-flags.cmake
      - cmake/caches/Windows-i686-clang.cmake
      - cmake/caches/Windows-i686-swift-flags.cmake
      - cmake/caches/Windows-x86_64-clang.cmake
      - cmake/caches/Windows-x86_64-swift-flags.cmake
schedules:
  - cron: "0 6 * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Nightly (6:00 AM) Build"
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/windows-sdk.yml
      - .ci/templates/windows-sdk.yml
      - cmake/caches/Windows-aarch64-clang.cmake
      - cmake/caches/Windows-aarch64-swift-flags.cmake
      - cmake/caches/Windows-armv7-clang.cmake
      - cmake/caches/Windows-armv7-swift-flags.cmake
      - cmake/caches/Windows-i686-clang.cmake
      - cmake/caches/Windows-i686-swift-flags.cmake
      - cmake/caches/Windows-x86_64-clang.cmake
      - cmake/caches/Windows-x86_64-swift-flags.cmake
jobs:
  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'
      branch: master
      toolchain: 7

      arch: 'armv7'
      host: 'arm'
      triple: 'armv7-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'
      branch: master
      toolchain: 7

      arch: 'aarch64'
      host: 'arm64'
      triple: 'aarch64-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'
      branch: master
      toolchain: 7

      arch: 'x86_64'
      host: 'x64'
      triple: 'x86_64-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      VisualStudio: 2019/Enterprise
      pool:
        vmImage: 'windows-2019'
      branch: master
      toolchain: 7

      arch: 'i686'
      host: 'x86'
      triple: 'i686-unknown-windows-msvc'
