name: Release Toolchains

on:
  workflow_dispatch:
  # Schedule to build a new release toolchain nightly.
  # Note: This is disabled on compnerd/swift-build as the
  # build times out when running the GitHub workflow in that repo.
  # schedule:
  #  - cron: "10 0 * * */1"

jobs:
  # Each job builds a release toolchain for a specific Swift version.
  build-release-5_10:
    # Note: GitHub requires the use of an 'owner/repo' path before the
    # workflow file path when we want to use a workflow from another branch.
    uses: compnerd/swift-build/.github/workflows/swift-toolchain.yml@release/5.10
    secrets:
      SYMBOL_SERVER_PAT: ${{ secrets.SYMBOL_SERVER_PAT }}
      CERTIFICATE: ${{ secrets.CERTIFICATE }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}
