name: SwiftFormat

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'SwiftFormat tag'
        required: true

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - swift_tag: DEVELOPMENT-SNAPSHOT-2023-05-22-a
            swift_branch: development

    steps:
      # Extract swift version (e.g., "swift-5.8-release" -> "5.8")
      - name: extract swift version
        run: |
          set SWIFT_VER=${{ matrix.swift_branch }}
          set SWIFT_VER=%SWIFT_VER:swift-=%
          set SWIFT_VER=%SWIFT_VER:-release=%
          echo %SWIFT_VER%
          echo SWIFT_VER=%SWIFT_VER%>> %GITHUB_ENV%
        shell: cmd

      # Build
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: refs/tags/${{ github.event.inputs.tag }}
          repository: nicklockwood/SwiftFormat

      - uses: compnerd/gha-setup-swift@main
        with:
          branch: ${{ matrix.swift_branch }}
          tag: ${{ matrix.swift_tag }}

      - name: test
        run: |
          swift test

      - name: build
        run: |
          swift build -c release

      # Package
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ vars.GITHUB_REF_NAME }}
          repository: ${{ vars.GITHUB_REPOSITORY }}
          path: ${{ github.workspace }}/SourceCache/${{ vars.GITHUB_REPOSITORY }}

      - uses: microsoft/setup-msbuild@v1.3.1

      - name: package
        run: |
          msbuild -restore ${{ github.workspace }}\SourceCache\${{ vars.GITHUB_REPOSITORY }}\installer-scripts\SwiftFormat.wixproj -nologo -p:Configuration=Release -p:ProductVersion=${{ github.event.inputs.tag }} -p:SWIFTFORMAT_BUILD=${{ github.workspace }}\.build\release -p:OutputPath=${{ github.workspace }}\artifacts -p:RunWixToolsOutOfProc=true

      # Release

      # Prepare the path to the msi file with forward slashes because action-gh-release
      # doesn't accept paths with backslashes.
      - name: prepare msi path
        run: |
          $MSI_PATH = cygpath -m ${{ github.workspace }}\artifacts\SwiftFormat.msi
          Echo MSI_PATH=$MSI_PATH | Out-File -FilePath ${env:GITHUB_ENV} -Encoding utf8 -Append

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          name: SwiftFormat-${{ github.event.inputs.tag }} (Swift ${{ env.SWIFT_VER }})
          tag_name: SwiftFormat-${{ github.event.inputs.tag }}-${{ matrix.swift_tag }}
          files: |
            .build/x86_64-unknown-windows-msvc/release/swiftformat.exe
            ${{ env.MSI_PATH }}
