name: swift-format

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - tag: 5.8-RELEASE
            branch: swift-5.8-release

    steps:
      # Build
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: refs/heads/release/5.8
          repository: apple/swift-format

      - uses: compnerd/gha-setup-swift@main
        with:
          branch: ${{ matrix.branch }}
          tag: ${{ matrix.tag }}

      - name: test
        run: |
          swift test -Xcc -IC:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\include -Xlinker -LC:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\lib

      - name: build
        run: |
          swift build -c release -Xcc -IC:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\include -Xlinker -LC:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\lib -Xswiftc -gnone

      # Package
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: refs/heads/main
          repository: apple/swift-installer-scripts
          path: ${{ github.workspace }}/SourceCache/swift-installer-scripts

      - uses: microsoft/setup-msbuild@v1.3.1

      - name: package
        run: |
          msbuild ${{ github.workspace }}/SourceCache/swift-installer-scripts/platforms/Windows/swift-format.wixproj -nologo -restore -p:Configuration=Release -p:ProductVersion=5.8 -p:SWIFT_FORMAT_BUILD=${{ github.workspace }}\.build\release -p:OutputPath=${{ github.workspace }}\artifacts -p:RunWixToolsOutOfProc=true

      # Release
      - run: |
          $MSI_PATH = cygpath -m ${{ github.workspace }}\artifacts\swift-format.msi
          Echo MSI_PATH=$MSI_PATH | Out-File -FilePath ${env:GITHUB_ENV} -Encoding utf8 -Append
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          name: swift-format-${{ matrix.tag }}
          tag_name: swift-format-${{ matrix.tag }}
          files: |
            .build/x86_64-unknown-windows-msvc/release/swift-format.exe
            ${{ env.MSI_PATH }}
