name: swift-format

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - tag: 5.7.2-RELEASE
            branch: swift-5.7.2-release

    steps:
      # Build
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: refs/tags/swift-5.7.2-RELEASE
          repository: apple/swift-format

      - uses: compnerd/gha-setup-swift@main
        with:
          branch: ${{ matrix.branch }}
          tag: ${{ matrix.tag }}

      - name: test
        run: |
          swift test -Xcc -IC:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\include -Xlinker -LC:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\lib

      - name: build
        run: |
          swift build -c release -Xcc -IC:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\include -Xlinker -LC:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\lib

      # Package
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: refs/heads/main
          repository: apple/swift-installer-scripts
          path: ${{ github.workspace }}/SourceCache/swift-installer-scripts

      - uses: microsoft/setup-msbuild@v1.0.3

      - name: package
        run: |
          msbuild ${{ github.workspace }}/SourceCache/swift-installer-scripts/platforms/Windows/swift-format.wixproj -nologo -p:Configuration=Release -p:ProductVersion=5.7.2 -p:SWIFT_FORMAT_BUILD=${{ github.workspace }}\.build\release -p:OutputPath=${{ github.workspace }}\artifacts -p:RunWixToolsOutOfProc=true

      # Release
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_release
        with:
          draft: true
          prerelease: true
          release_name: swift-format-${{ matrix.tag }}
          tag_name: swift-format-${{ matrix.tag }}
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: application/octet-stream
          asset_name: swift-format.exe
          asset_path: .build\x86_64-unknown-windows-msvc\release\swift-format.exe
          upload_url: ${{ steps.create_release.outputs.upload_url }}
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: application/octet-stream
          asset_name: swift-format.msi
          asset_path: ${{ github.workspace }}\artifacts\swift-format.msi
          upload_url: ${{ steps.create_release.outputs.upload_url }}
